### ISSUE TITLE
Docs need link to tutorial

### ISSUE THREAD

**Issue by BryanCrotaz** [iswix-llc/iswix-tutorials#16]
The readme says there are tutorials and samples. But it only links to a sample, which is enormously complex and needs explanation of what each step does and how they crosslink.

This is the link at the bottom for Wix 4 - I was really excited to find this tutorial having spent two weeks wading through the weeds of Wix 4 and not being able to get an installer building at all!

https://github.com/iswix-llc/iswix-tutorials/tree/master/WiX-v4-HeatWave

I can't find the tutorial in here - can someone who knows the project add a direct link to it?

**Comment by chrpai** [comment]
I haven't gotten around to creating the tutorials for v4.  They do exist for v3.  They are in the README.md files that are in each tutorial directory.  Would you like to help write them?

**Comment by chrpai** [comment]
Complete
