### ISSUE TITLE
Target folder for xcopy is wrong

### ISSUE THREAD

**Issue by tsahi** [iswix-llc/iswix-tutorials#2]
The service installer documentation at https://github.com/iswix-llc/iswix-tutorials/tree/master/windows-service (which, btw, should naturally be in the Wiki and not in the repo), states you should add `xcopy /iery "$(TargetDir)*.*" "$(SolutionDir)..\Installer\Deploy"` to your Windows Service project. So if your repo has this structure:
```
/
+-/WindowsService
```
this command will copy the output to 

    /../Installer/Deploy

i.e. one folder above the repo root and down to Installer/Deploy.

The installer project is expected to be created in `/Installer`, so that it's two projects are in `/Installer/WindowsService` and `/Installer/WindowsServiceMM`.

Then, in the WindowsServiceMM project, the `SourceDir` variable points to `..\Deploy`, which is resolved to `/Installer/Deploy`, which is a different location from where the files where copied to.

**Comment by tsahi** [comment]
it would also be useful to clear the target folder from leftovers from previous builds: `del "$(SolutionDir)..\Installer\Deploy\*.*" /q`

**Comment by tsahi** [comment]
more exact, `del "$(SolutionDir)..\Installer\Deploy\*.*" /q

**Comment by chrpai** [comment]
The commands are going to vary a little based on how you set your project up.   It's more of a concept... just some basic plumbing to get your files staged  and create a model for what to deploy.  There are many ways to achieve this.
